apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue
                port:
                  number: 80
    - host: localhost
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue
                port:
                  number: 80
