apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - ingress.yaml
  - db/deployment.yaml
  - db/service.yaml
  - django/deployment.yaml
  - django/migrate-job.yaml
  - django/service.yaml
