apiVersion: v1
kind: Secret
metadata:
  name: myapp-env
  namespace: myapp
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-myapp"
  DB_PASSWORD: "myapp_password"
  POSTGRES_PASSWORD: "myapp_password"
