apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: myapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vue
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: myapp-config
                  key: ALLOWED_HOSTS
          ports:
            - containerPort: 5173
