apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
  namespace: myapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vue
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
